In [60]:
import pandas as pd
# reads csv files into dataframes
df1 = pd.read_csv("CRMLSSold202507.csv")
df2 = pd.read_csv("CRMLSSold202508.csv")
df3 = pd.read_csv("CRMLSSold202509.csv")
df4 = pd.read_csv("CRMLSSold202510.csv")
df5 = pd.read_csv("CRMLSSold202511.csv")
df6 = pd.read_csv("CRMLSSold202512.csv")
# Creates train test split
df_train = pd.concat([df1, df2, df3, df4, df5], axis = 0)
df_test = df6
# Narrows down the data
df_train = df_train[(df_train["PropertyType"] == "Residential") & (df_train["PropertySubType"] == "SingleFamilyResidence")]
df_test = df_test[(df_test["PropertyType"] == "Residential") & (df_test["PropertySubType"] == "SingleFamilyResidence")]
# df_to_use.columns
# df_to_use.shape
cols = ["ClosePrice", "PropertySubType", "YearBuilt", "BathroomsTotalInteger", "BedroomsTotal", "NewConstructionYN", "LotSizeSquareFeet"]
df_filtered_train = df_train[cols]
df_test_filtered = df_test[cols]

In [61]:
#finds number of na values for each feature
df_filtered_train.isna().sum()
df_test_filtered.isna().sum()

ClosePrice                 0
PropertySubType            0
YearBuilt                  6
BathroomsTotalInteger      0
BedroomsTotal              0
NewConstructionYN        760
LotSizeSquareFeet        156
dtype: int64

In [62]:
df_filtered_train["LotSizeSquareFeet"][df_filtered_train["LotSizeSquareFeet"] == 0] = None
df_filtered_train = df_filtered_train.dropna(subset = ["YearBuilt", "BathroomsTotalInteger", "LotSizeSquareFeet"])

df_test_filtered["LotSizeSquareFeet"][df_test_filtered["LotSizeSquareFeet"] == 0] = None
df_test_filtered = df_test_filtered.dropna(subset = ["YearBuilt", "BathroomsTotalInteger", "LotSizeSquareFeet"])
df_test_filtered

C:\Users\jehil\AppData\Local\Temp\ipykernel_10964\834665494.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_filtered_train["LotSizeSquareFeet"][df_filtered_train["LotSizeSquareFeet"] == 0] = None
C:\Users\jehil\AppData\Local\Temp\ipykernel_10964\834665494.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered_train["LotSizeSquareFeet"][df_filtered_train["LotSizeSquareFeet"] == 0] = None
C:\Users\jehil\AppData\Local\Temp\ipykernel_10964\834665494.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered_train["LotSizeSquareFeet"][df_filtered_train["LotSizeSquareFeet"] == 0] = None
C:\Users\jehil\AppData\Local\Temp\ipykernel_10964\834665494.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_test_filtered["LotSizeSquareFeet"][df_test_filtered["LotSizeSquareFeet"] == 0] = None
C:\Users\jehil\AppData\Local\Temp\ipykernel_10964\834665494.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test_filtered["LotSizeSquareFeet"][df_test_filtered["LotSizeSquareFeet"] == 0] = None
C:\Users\jehil\AppData\Local\Temp\ipykernel_10964\834665494.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test_filtered["LotSizeSquareFeet"][df_test_filtered["LotSizeSquareFeet"] == 0] = None

,ClosePrice,PropertySubType,YearBuilt,BathroomsTotalInteger,BedroomsTotal,NewConstructionYN,LotSizeSquareFeet
0,1998000.0,SingleFamilyResidence,1968.0,2.0,4.0,False,10080.0
2,2214421.0,SingleFamilyResidence,1957.0,4.0,4.0,False,34745.0
3,1200000.0,SingleFamilyResidence,1978.0,2.0,4.0,False,6600.0
7,3100000.0,SingleFamilyResidence,2025.0,3.0,5.0,False,8262.0
9,2900000.0,SingleFamilyResidence,2023.0,4.0,5.0,False,9222.0
...,...,...,...,...,...,...,...
20494,640000.0,SingleFamilyResidence,1992.0,3.0,3.0,False,105281.0
20496,12000000.0,SingleFamilyResidence,2004.0,4.0,5.0,False,15118.0
20510,600000.0,SingleFamilyResidence,2004.0,2.0,3.0,False,871200.0
20511,380000.0,SingleFamilyResidence,1971.0,2.0,3.0,False,9620.0
20536,842000.0,SingleFamilyResidence,1966.0,2.0,3.0,False,7275.0

In [64]:
df_filtered_train.isna().sum()
df_test_filtered.isna().sum()

ClosePrice                 0
PropertySubType            0
YearBuilt                  0
BathroomsTotalInteger      0
BedroomsTotal              0
NewConstructionYN        759
LotSizeSquareFeet          0
dtype: int64

In [ ]:
# df_filtered.isna().sum()
# 5108/df_filtered.shape[0]

0.07733535200605601

In [65]:
# Encodes new construction variable into binary variable
df_filtered_train["NewConstructionYN"][df_filtered_train["NewConstructionYN"] == False] = 0
df_filtered_train["NewConstructionYN"][df_filtered_train["NewConstructionYN"] == True] = 1
df_filtered_train["NewConstructionYN"].value_counts()

df_test_filtered["NewConstructionYN"][df_test_filtered["NewConstructionYN"] == False] = 0
df_test_filtered["NewConstructionYN"][df_test_filtered["NewConstructionYN"] == True] = 1
df_test_filtered["NewConstructionYN"].value_counts()

C:\Users\jehil\AppData\Local\Temp\ipykernel_10964\1230365001.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_filtered_train["NewConstructionYN"][df_filtered_train["NewConstructionYN"] == False] = 0
C:\Users\jehil\AppData\Local\Temp\ipykernel_10964\1230365001.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_filtered_train["NewConstructionYN"][df_filtered_train["NewConstructionYN"] == True] = 1
C:\Users\jehil\AppData\Local\Temp\ipykernel_10964\1230365001.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered_train["NewConstructionYN"][df_filtered_train["NewConstructionYN"] == True] = 1
C:\Users\jehil\AppData\Local\Temp\ipykernel_10964\1230365001.py:6: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_test_filtered["NewConstructionYN"][df_test_filtered["NewConstructionYN"] == False] = 0
C:\Users\jehil\AppData\Local\Temp\ipykernel_10964\1230365001.py:7: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_test_filtered["NewConstructionYN"][df_test_filtered["NewConstructionYN"] == True] = 1
C:\Users\jehil\AppData\Local\Temp\ipykernel_10964\1230365001.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test_filtered["NewConstructionYN"][df_test_filtered["NewConstructionYN"] == True] = 1

NewConstructionYN
0    9110
1     416
Name: count, dtype: int64

In [69]:
#scales numerical variables only in training set
from sklearn.preprocessing import StandardScaler
df_filtered_train.dtypes
num_cols = ["YearBuilt", "BathroomsTotalInteger", "BedroomsTotal", "LotSizeSquareFeet"]
scaler = StandardScaler()
df_filtered_train[num_cols] = scaler.fit_transform(df_filtered_train[num_cols])
df_filtered_train

,ClosePrice,PropertySubType,YearBuilt,BathroomsTotalInteger,BedroomsTotal,NewConstructionYN,LotSizeSquareFeet
3,1040000.0,SingleFamilyResidence,0.463099,0.337932,-0.508596,0,-0.022750
4,2400000.0,SingleFamilyResidence,-0.773762,0.337932,-0.508596,0,-0.022364
8,1908500.0,SingleFamilyResidence,-0.264466,0.337932,0.530871,0,-0.022840
9,1050000.0,SingleFamilyResidence,-0.992031,1.223993,0.530871,NaN,-0.022120
10,5900000.0,SingleFamilyResidence,0.899638,0.337932,-0.508596,0,-0.022492
...,...,...,...,...,...,...,...
19057,675000.0,SingleFamilyResidence,0.135695,-0.548130,-0.508596,NaN,-0.018823
19060,805000.0,SingleFamilyResidence,-1.901488,-0.548130,-0.508596,0,-0.022649
19071,700000.0,SingleFamilyResidence,-0.882897,0.337932,2.609803,0,-0.022666
19077,215000.0,SingleFamilyResidence,-0.737384,-0.548130,-0.508596,0,-0.011483
19083,1175000.0,SingleFamilyResidence,1.554447,1.223993,0.530871,0,-0.022770

In [72]:
#remove bottom 0.5% and top 0.5% of ClosePrice values in the training and testing sets separately
c_price = "ClosePrice"
train_low = df_filtered_train[c_price].quantile(0.005)
train_high = df_filtered_train[c_price].quantile(0.995)
df_train_cleaned = df_filtered_train[(df_filtered_train[c_price] >= train_low) & (df_filtered_train[c_price] <= train_high)]
df_train_cleaned

,ClosePrice,PropertySubType,YearBuilt,BathroomsTotalInteger,BedroomsTotal,NewConstructionYN,LotSizeSquareFeet
3,1040000.0,SingleFamilyResidence,0.463099,0.337932,-0.508596,0,-0.022750
4,2400000.0,SingleFamilyResidence,-0.773762,0.337932,-0.508596,0,-0.022364
8,1908500.0,SingleFamilyResidence,-0.264466,0.337932,0.530871,0,-0.022840
9,1050000.0,SingleFamilyResidence,-0.992031,1.223993,0.530871,NaN,-0.022120
10,5900000.0,SingleFamilyResidence,0.899638,0.337932,-0.508596,0,-0.022492
...,...,...,...,...,...,...,...
19057,675000.0,SingleFamilyResidence,0.135695,-0.548130,-0.508596,NaN,-0.018823
19060,805000.0,SingleFamilyResidence,-1.901488,-0.548130,-0.508596,0,-0.022649
19071,700000.0,SingleFamilyResidence,-0.882897,0.337932,2.609803,0,-0.022666
19077,215000.0,SingleFamilyResidence,-0.737384,-0.548130,-0.508596,0,-0.011483
19083,1175000.0,SingleFamilyResidence,1.554447,1.223993,0.530871,0,-0.022770

In [73]:
#test set done separately
test_low = df_test_filtered[c_price].quantile(0.005)
test_high = df_test_filtered[c_price].quantile(0.995)
df_test_cleaned = df_test_filtered[(df_test_filtered[c_price] >= test_low) & (df_test_filtered[c_price] <= test_high)]
df_test_cleaned

,ClosePrice,PropertySubType,YearBuilt,BathroomsTotalInteger,BedroomsTotal,NewConstructionYN,LotSizeSquareFeet
0,1998000.0,SingleFamilyResidence,1968.0,2.0,4.0,0,10080.0
2,2214421.0,SingleFamilyResidence,1957.0,4.0,4.0,0,34745.0
3,1200000.0,SingleFamilyResidence,1978.0,2.0,4.0,0,6600.0
7,3100000.0,SingleFamilyResidence,2025.0,3.0,5.0,0,8262.0
9,2900000.0,SingleFamilyResidence,2023.0,4.0,5.0,0,9222.0
...,...,...,...,...,...,...,...
20490,479500.0,SingleFamilyResidence,1990.0,2.0,2.0,0,1745449.0
20494,640000.0,SingleFamilyResidence,1992.0,3.0,3.0,0,105281.0
20510,600000.0,SingleFamilyResidence,2004.0,2.0,3.0,0,871200.0
20511,380000.0,SingleFamilyResidence,1971.0,2.0,3.0,0,9620.0
20536,842000.0,SingleFamilyResidence,1966.0,2.0,3.0,0,7275.0